### PR TITLE
Fix wildcard exports, take 2

### PR DESCRIPTION
**Pull request by valscion**
This PR incorporates the stuff in #79 and the usage tests, too.

Effectively closes #79

### CODE REVIEW

**Comment by valscion** [comment]
Oh there seems to be a weird file present from https://github.com/joefiorini/babel-plugin-rewire/commit/f0056a7a66d3aae7e55f9766af36f507e5143be0 — I'll remove it.

**Comment by valscion** [comment]
Uh, weird that travis fails. It failed on my machine, too, initially, but after I ran `npm install` it went away. Any idea what might be causing that?

**Comment by joefiorini** [comment]
@valscion Thanks for taking care of this!

**Comment by speedskater** [comment]
@joefiorini @valscion thanks to both of you for your help and contribution. Would you like to be mentioned as a contributer?

**Comment by valscion** [comment]
Having my name in https://github.com/speedskater/babel-plugin-rewire/graphs/contributors is enough. Thanks anyway :)

**Pull request merged**
