### PR TITLE
Adding configuration option for ignoring rewiring identifiers

### LINKED ISSUE #117: rc-2 keeps browserify from finding required files through other packages
We use a package [proxyquireify](https://github.com/thlorenz/proxyquireify) in order to stub out module dependencies as well as babel-plugin-rewire. 

These have worked just fine together in past versions of this module, however now the transformation to the calls seems to keep browserify from detecting those modules bring required and including it in the bundle. 

I'll try to create a failing test, but I just wanted to get this issue put up in the mean time.

### PR DESCRIPTION
**Pull request by TheSavior**
Fixes #117 

Can now specify configuration options for the plugin to specify identifiers it shouldn't rewire:

```
"plugins": [
  ["rewire", {
    ignoredIdentifiers: ['ignoredIdentifier1', 'ignoredIdentifier2']
  }],
  "syntax-async-functions",
  "syntax-flow",
  "syntax-jsx",
  "transform-export-extensions"
]
```

### CODE REVIEW

**Comment by speedskater** [comment]
@TheSavior Thanks for this PR. I will merge it ASAP.

**Comment by TheSavior** [comment]
@speedskater Please review this

**Comment by kentcdodds** [comment]
Note: This pull request fixes #128 :-)
https://github.com/kentcdodds/rewire-lodash-bug/pull/1

**Comment by kentcdodds** [comment]
@TheSavior, looking at the repo activity, it looks like @speedskater may be a bit busy. What would you think about doing a release of your fork (with an obvious name of: `babel-plugin-rewire-fork` or something) so we can have this feature until @speedskater can get to it (or give access to someone else to do merges and releases).

**Comment by speedskater** [comment]
@all sorry for the delay. Will merge this tomorrow and publish a new release

**Comment by kentcdodds** [comment]
Thanks @speedskater. I understand how OSS can be thankless, so thanks for creating this!

**Comment by kentcdodds** [comment]
FYI and apologies. I've found a workaround with [`proxyquire`](http://npm.im/proxyquire). It's a little less heavy handed of a solution. Even though I really like the API of this plugin. Anyway, I no longer have a use case for this.

Thanks anyway!

**Comment by speedskater** [comment]
@kentcdodds thanks for your feedback and sorry for the inconvenience.
@TheSavior thanks for providing the PR its merged now. Sorry for the delay.

**Pull request merged**
