### PR TITLE
Added information on how to use with isparta

### PR DESCRIPTION
**Pull request by DLMR**

### CODE REVIEW

**Comment by TheSavior** [comment]
Do you believe this documentation belongs more here, or on isparta's repo?

**Comment by DLMR** [comment]
To some extent more in isparta's since it's about how you should think about it in terms of Babel configuration. This problem is not specific to this plugin but all potential plugins and other configuration alternativs that you can do in Babel.

With that said I still think a mention about this is good in this repo to avoid _"stupid"_ issues when using it together with isparta since it will be a quite common paring, they are both related to testing together with Babel.

**Comment by speedskater** [comment]
@DLMR thanks for your effort. 
@DLMR, @TheSavior I think theoretically it would make sense in the isparta documentation. But from a practical point of view I think it makes perfect sense in this documentation. Perhaps we should put it under a section called "combining with other plugins/tools" and each tool in this case isparta as a subsection.
What do you think?

**Comment by TheSavior** [comment]
:+1:

**Comment by DLMR** [comment]
I agree, more logical to have that information under a separate section. Also updated the wording a bit.

**Pull request merged**
