### PR TITLE
return revert function from __set__ with object

### LINKED ISSUE #197: __set__ with an object does not return revert function
Calling `__set__` with a string variableName returns a function to revert as expected, but when passing an object no revert function is returned.

### PR DESCRIPTION
**Pull request by twhitbeck**
resolves #197

### CODE REVIEW

**Comment by twhitbeck** [comment]
@nene I think you originally contributed the `__set__` with object functionality. Is there a reason you left out the revert? Or did that come later?

**Comment by nene** [comment]
I guess I did not have a need for reverting.

**Comment by speedskater** [comment]
@twhitbeck Thank your for your PR and sorry for my very late reply. I finally managed to merged it into the 1.2.0 branch and puglished 1.2.0-rc.1 on npm as a prerelease. I also added you as a contributor to the README. I hope this is okay with you?
Could you please test this release in your code bases. If I won't get any negativ feedback till next monday I will convert it to the final 1.2.0 and will then merge it onto master.

**Comment by twhitbeck** [comment]
@speedskater that's great, thanks! What's up with the failing tests? do you need me to rebase this PR?

**Pull request closed without merging**
