### PR TITLE
Avoid rewiring LHS of ForInStatements

### PR DESCRIPTION
**Pull request by mikesherov**

### CODE REVIEW

**Comment by mikesherov** [comment]
Thanks again for the great plugin! Please consider accepting this PR and releasing a new version at your earliest convenience. Thanks again!

**Comment by mikesherov** [comment]
Actually, I need to add forOfStatements as well.

**Comment by mikesherov** [comment]
ForOfStatements will require a lot more work actually, so I'd love to land this fix for ForIn and later I can address ForOfStatement.

**Comment by speedskater** [comment]
@mikesherov thank your for providing the PR and the transformation test. I will merge your additions today. I will first write a short sample test.

**Comment by speedskater** [comment]
@mikesherov Merged your branch onto version 1.1.0 branch.

**Comment by speedskater** [comment]
@mikesherov Merged onto 1.1.0 branch will be part of the next build (today).

**Pull request closed without merging**
